---
title: "Empirical studies citing Lakens' (2017) equivalence primer"
author: "Peder M Isager"
date: "October 24, 2017"
output: html_document
---


The following studies are all empirical studies that cites Lakens' (2017) equivalence primer. Studies that appear to be reviews or theoretical pieces were not included. A short description of the study, and a short description of the bound criterion used, is provided for each study. 


## Kunz et al. (2017)

The authors study how hematologic properties of blood changes during long-duration spaceflight. Equivalence tests were applied in a within subject design to test whether various hematologic properties would remain stable over prolonged periods (days - weeks) of spaceflight. 

Equivalence bounds were set based on the within-person coefficient of variation for each hematologic parameter in a group of 852 non-institutionalized subjects, reported by Lacher et al. (2012). 


## Mirabella et al. (2017)

The authors study inhibitory control's reliance upon a right-lateralized brain pathway by studying inhibition function in left and right lateralized Parkinson patients. 

Equivalence bounds were set to the bounds that the study had 80% power to reject a true effect of 0 with.


## Schumann et al. (2017)

The authors assessed moderators of successful computer-mediated intergroup contact (CMIC).  

Equivalence bounds were based on Cohen's d benchmarks of −0.50 and d = 0.50. 


## Protzko and Schooler (2017)

Studied the relationship between researcher "caliber" (defined as h-index), and ability to successfully replicate (defined as effect size in replication). 

Equivalence bounds were not formally defined. Instead, 90% CIs were calculated and found to be very narrow (beta of +/- .005 around a mean of .00003). The authors then state (something to the effect of) that effects within this interval is practically equivalent to zero. 


## Petsko and Bondenhausen (2017)

The authors attempted to replicate the race-crime congruency effect, and study the influence of sexual orientation on this effect. 

Equivalence bounds were set to the bounds that the study had 80% power to reject a true effect of 0 with (using the power calculator for equivalence tests). 


## Müller and Gregorick (2017)

The authors study the effect of a feedback program on student grammar in academic writing.

Equivalence bounds were set to d = +/- 0.25 standardized gain (reduction in errors). Their explanation is that this represents an educationally meaningful effect, but the justification appears to be based on expert advice (Wolf, 1986) rather than theoretical or empirical evidence. 

## Mc Gee et al. (2017)

The authors studied the difference between age groups on the Sense of Coherence scale. 

Equivalence bounds were set to d = +/- 0.4. Sample size and power of 80% is mentioned, but does not make it clear exactly how the authors set the bounds: *"Given the current sample size and an achieved power of 80%, modest lower and upper equivalence bounds of Cohen’s d = ¡0.4 and d = 0.4 were set as the smallest effect size of interest"*. 


## Kordsmeyer and Penke (2017)

The authors studied the relationship between bodily assumetries and indicators of quantitative mating success. 

Equivalence bounds were based on mean effects from previous meta-analyses of similar effects. 


## Matheson et al (2017)

The authors compare different methods for assessing PET receptor binding (of a specific ligand to a specific protein) compared to gold standard. 

Equivalence tests are referenced for future research, but not utilized in the study.

## Wimmer & Poldrack (2017)

The authors studied the effect of time distribution on learning effects in feedback training.

Equivalence bounds appears to be set based on the effect that the studies have 80% power to detect, but it is not perfectly clear based on the language in the paper whether this is the case: *"We used bounds of Cohen’s d = 0.51 (Study1) or d = 0.53 and d = 0.54 (Study 2), where power to detect an effect in the included group of participants is estimated to be 80%."*

Used TOSTER in R


## Geerse et al. (2017)

the authors studied the reliability of the eKinect v2 Sensor in quantifying gait, based on foot placement locations.

Equivalence bounds were based on the smallest "limits of agreement" (?) in a previous study on similar effects by the same authors. 

Used TOSTER in Jamovi


## Brown et al. (2017)

The authors studied the effect of behavioral inhibition system (BIS) activation on likelihood to convict in a lab-constructed jury situation. 

Equivalence bounds were based on Cohen's d benchmarks of −0.50 and d = 0.50. This is assumed, but the authors never explicitly state the justification behind the chosen equivalence bound. 
