---
title: "Simulating NHST and TOST"
output:
  html_document: default
  html_notebook: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r}
options(scipen=999)
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```
#Simulating one-sample t-tests


```{r}
require(TOSTER)
n <- 50 #set sample size
low_eqbound=-0.3
high_eqbound=0.3
sd_true<-1
m_true<-0.0
mu<-0.0
alpha<-0.05

require("TOSTER")
n<-powerTOSTone(alpha=alpha, statistical_power=0.8, low_eqbound_d=-low_eqbound, high_eqbound=0.3)
n<-ceiling(n)


nSims <- 1000000 #number of simulated experiments
pttest<-numeric(nSims) #set up empty container for all simulated p-values
ptost<-numeric(nSims) #set up empty container for all simulated p-values
tlist<-numeric(nSims) #set up empty container for all simulated p-values
p1list<-numeric(nSims) #set up empty container for all simulated p-values
p2list<-numeric(nSims) #set up empty container for all simulated p-values
LLlist<-numeric(nSims)
ULlist<-numeric(nSims)

for(i in 1:nSims){ #for each simulated experiment
  x<-rnorm(n = n, mean = m_true, sd = sd_true) #Simulate data with specified mean, standard deviation, and sample size
  m<-mean(x)
  sd<-sd(x)
  degree_f<-n-1
  t1<-(m-mu-low_eqbound)/(sd/sqrt(n))# t-test
  p1<-pt(t1, degree_f, lower=FALSE) 
  p1list[i]<-p1
  t2<-(m-mu-high_eqbound)/(sd/sqrt(n)) #t-test
  p2<-pt(t2, degree_f, lower=TRUE) 
  p2list[i]<-p2
  t<-(m-mu)/(sd/sqrt(n))
  tlist[i]<-t
  pttest[i]<-2*pt(-abs(t), df=degree_f)
  LL90<-(m-mu)-qt(1-alpha, degree_f)*(sd/sqrt(n))
  LLlist[i]<-LL90
  UL90<-(m-mu)+qt(1-alpha, degree_f)*(sd/sqrt(n))
  ULlist[i]<-UL90
  ptost[i]<-max(p1,p2)
  ttost<-ifelse(abs(t1) < abs(t2), t1, t2) #Get lowest t-value for summary TOST result
}

#P-value distribution TOST
hist(ptost, breaks=500, xlim=c(0,1))
sum(ptost<0.05)/nSims #Power for TOST

sum(LLlist>=low_eqbound&ULlist<=high_eqbound)/nSims #Same power or Type 1 error, now based on CI

#Combine p-values from TOST and NHST

p<-data.frame(ptost,pttest)
#look only at significant TOST results
p_sig_TOST<-p[which(ptost<alpha),]
#Plot the p-values for the NHST t-test, but only those for significant TOT results. 
hist(p_sig_TOST$pttest, breaks=100)

#plot p-value distribution for TOST - looks peculiar
#Dat can only be so far removed from one bound, before it gets closer to the other bound. So p = 0.0000001 often not possible 
# (need to widen bounds for that, or increase N)
hist(p_sig_TOST$ptost, breaks=100)

#How often is a test significant AND equivalent?
nrow(p[which(ptost<alpha & pttest<alpha),])/nSims

#plot p-values against each other for TOST and NHST
plot(ptost,pttest)

```