---
title: "SNEQ_Lynott_example"
author: "Peder M Isager"
date: "October 17, 2017"
output: html_document
---

## Example 4: Statistically Inferior and Not Statistically Different
```{r include=FALSE}
se <- sqrt((0.75 * (1 - 0.75)) / 26 + (0.46 * (1 - 0.46)) / 27)  # Calculate the (unpooled) standard error
crit.z <- qnorm(1 - (0.05 / 2))  # Determine the critical z for a two-tailed test with alpha = 0.05


crit.diff <- crit.z * se  # Convert z to the critical difference



library(TOSTER)  # Install TOSTER using devtools::install_github("Lakens/TOSTER"), or download TOSTtwo.prop.R from https://github.com/Lakens/TOSTER/tree/master/R and then source it. 


#  We first load the data and exclude cases to only include cases that did not meet the authors' exclusion criteria.
lynott.data <- read.csv("NSEQ_Lynott_example_data.csv")
lynott.data <- lynott.data[lynott.data$include1 == 1,]


#  We then calculate the summary statistics from the data that we need in the TOST calculation below
n.hot            <- sum(lynott.data$packtype == 1)
n.cold           <- sum(lynott.data$packtype == 0)
selfish.hot  <- sum(lynott.data$selfish[lynott.data$packtype == 1] == 1, na.rm = TRUE) / n.hot
selfish.cold <- sum(lynott.data$selfish[lynott.data$packtype == 0] == 1, na.rm = TRUE) / n.cold
diff <- selfish.hot - selfish.cold

#  We can now run the TOST!
tost <- TOSTtwo.prop(prop1 = selfish.cold,
                         prop2 = selfish.hot,
                         n1        = n.cold,
                         n2        = n.hot,
                         low_eqbound  = -crit.diff,
                         high_eqbound = crit.diff,
                         alpha = 0.05)

```


Lynott et al. (2014) conducted a study to investigate the effect of being exposed to physically warm or cold stimuli on subsequent judgments related to interpersonal warmth and prosocial behavior (replicating Williams and Bargh, 2008). They observed that `r round(selfish.cold,2)*100`\% of participants who received a cold pack ($n_{cold}=`r round(n.cold,2)`$) opted to receive a reward for themselves, while `r round(selfish.hot,2)*100`\% of participants who received a warm pack ($n_{hot}=`r n.hot`$) did the same. In a z-test for the difference between the proportions, this effect is not statistically significant ($Diff=`r round(diff,2)`$, $Z=`r round(tost$NHST_z,2)`$, $p=`r round(tost$NHST_p,2)`$). Having obtained a non-significant result, we are left with the same two  alternatives as in example 3. 

In this case, it is not really clear what an objective criterion for the smallest effect size of interest could be. However, since this is a replication, we could decide that we do not care about an effect if the difference is smaller than the smallest effect that the original study could detect. This essentially means that we use the critical z value (~1.96 in a two-tailed test with an alpha of 0.05) as our bounds ($\Delta = +/- `r round(qnorm(1-0.05/2),2)`$). To figure out what difference corresponds to a critical z in the original study, we multiply critical z with the standard error:


Having determined the SESOI, we may also decide that since this is a replication, we are only interested in whether the effect of receiving a cold pack is significantly *lower* than the smallest detectable effect of the original study. In this case, we can still use a TOST to analyse the data, but we only need to consider the test against $\Delta_{upper}$ because an effect with CIs crossing $\Delta_{lower}$ can still be *lower* than the original effect. 



We find that the test against $\Delta_{upper}$ is `r ifelse(tost$TOST_p2 < tost$alpha, "significant", "non-significant")`, $z =$ `r round(tost$TOST_z2, 2)`, $p =$ `r ifelse(round(tost$TOST_p2, 3) >= 0.001, paste("=", round(tost$TOST_p2, 2)), "< 0.001")` (see figure 2D). Thus, we can conclude that the statistically non-significant effect is also statistically inferior to our SESOI. 
